
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false
        username: root
        password: Siva@1234
        driver-class-name: com.mysql.cj.jdbc.Driver
        hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect

    jpa.hibernate.ddl-auto: update



management:
    endpoints:
        web:
            exposure:
                #include: "*"
                include: "health,beans,metrics,info"
                #exclude: "caches" remove some endpoints
                #base-path: "/management" to change the base path from /actuator to /management
    endpoint:
        health:
            show-details: always


